apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ohmyform
  namespace: ohmyform
spec:
  params: []
  resources: []
  workspaces:
    - name: shared-workspace
      optional: true
  tasks:
    - name: buildah
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: image: >-
            image-registry.openshift-image-registry.svc:5000/ohmyform/ohmyform:latest
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - git-clone
    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/marcoklaassen/ohmyform.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
        - name: userHome
          value: /tekton/home
      workspaces:
        - name: output
          workspace: shared-workspace
  finally: []
